#
# Spring
#
spring.application.name=${APP_NAME:@project.artifactId@}
spring.application.version=${APP_VERSION:@project.version@}

server.port=${SERVER_PORT:18082}
server.forward-headers-strategy=framework

#
# Database
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/npca?currentSchema=abs}
spring.datasource.username=${DB_USER:npca}
spring.datasource.password=${DB_PASS:npca}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.check_nullability=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate

#
# Liquibase
#
liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog.yaml

#
# Logging
#
logging.level.root=${LOGGING_LEVEL_DEFAULT:INFO}
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.org.postgresql=WARN
logging.level.org.apache.tomcat.util=WARN

#
# Swagger
#
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.show-actuator=false

#
# Jwt-starter
#
jwt-starter-properties.public-key=${RSA_PUBLIC_KEY}
jwt-starter-properties.algorithm-family=RSA
jwt-starter-properties.algorithm-type=RSA256
jwt-starter-properties.error-code-response=2001
jwt-starter-properties.error-message-response=AccessToken invalid

#
# Cors
#
cors.allowed-origins=${ALLOWED_ORIGINS}
cors.allowed-headers=${ALLOWED_HEADERS}
cors.allowed-methods=${ALLOWED_METHODS}

#
#reddis
#
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.password=${REDIS_PASS:npca}

#cache
cache.ttl=86400
cache.scheduler.cron=0 0 0 * * *
