/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.56).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

package com.example.absservice.swagger.api;

import java.io.*;
import java.util.*;

import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.*;

import com.fasterxml.jackson.databind.*;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.media.*;
import io.swagger.v3.oas.annotations.responses.*;
import io.swagger.v3.oas.annotations.security.*;
import org.springframework.http.*;
import org.springframework.validation.annotation.*;
import org.springframework.web.bind.annotation.*;

import com.example.absservice.swagger.dto.*;

@Validated
public interface DictionariesApi {

    Logger log = LoggerFactory.getLogger(DictionariesApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Получение справочных значений для фильтров вклада", description = "Запрос на получение продуктов по заданными параметрам", security = {
        @SecurityRequirement(name = "BearerAuth")}, tags = {"ABS"})
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Успешный ответ", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ParametersDto.class))),

        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

        @ApiResponse(responseCode = "404", description = "Internal server error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

        @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class)))})
    @RequestMapping(value = "/dictionaries",
        produces = {"application/json"},
        method = RequestMethod.GET)
    default ResponseEntity<ParametersDto> dictionariesGet() {
        if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get()
                        .readValue(
                            "{\r\n  \"capitalizationPeriods\" : [ \"Ежедневно\", \"Ежеквартально\", \"Ежемесячно\", \"Ежегодно\" ],\r\n  \"periods\" : [ 31, 62, 92, 122, 182, 243, 273, 365, 731, 1098 ],\r\n  \"currencies\" : [ \"RUB\", \"CNY\", \"USD\", \"EUR\" ]\r\n}",
                            ParametersDto.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn(
                "ObjectMapper or HttpServletRequest not configured in default DictionariesApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

