/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.56).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

package com.example.absservice.swagger.api;

import java.io.*;
import java.util.*;


import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.*;

import com.fasterxml.jackson.databind.*;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.media.*;
import io.swagger.v3.oas.annotations.responses.*;
import io.swagger.v3.oas.annotations.security.*;
import org.springframework.http.*;
import org.springframework.validation.annotation.*;
import org.springframework.web.bind.annotation.*;

import com.example.absservice.swagger.dto.*;

@Validated
public interface FinancialProductsApi {

    Logger log = LoggerFactory.getLogger(FinancialProductsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Выборка финансовых продуктов", description = "Запрос на получение продуктов по заданными параметрам", security = {
        @SecurityRequirement(name = "BearerAuth")}, tags = {"ABS"})
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Успешный ответ с выборкой фин. продуктов", content = @Content(mediaType = "application/json", schema = @Schema(implementation = FinancialProductsResponseDto.class))),

        @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class))),

        @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiErrorResponseDto.class)))})
    @RequestMapping(value = "/financial-products",
        produces = {"application/json"},
        method = RequestMethod.GET)
    default ResponseEntity<FinancialProductsResponseDto> financialProductsGet() {
        if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get()
                        .readValue(
                            "{\r\n  \"products\" : [ {\r\n    \"minSum\" : 5000,\r\n    \"maxSum\" : 5000000,\r\n    \"financialProduct\" : {\r\n      \"period\" : 62,\r\n      \"canWithdrawal\" : true,\r\n      \"name\" : \"АТБ. Вклад\",\r\n      \"currency\" : \"RUB\",\r\n      \"id\" : 12345,\r\n      \"canDeposit\" : true,\r\n      \"category\" : \"Клиент\",\r\n      \"percent\" : 15.3,\r\n      \"capitalizationPeriod\" : \"Ежедневно\",\r\n      \"capitalizationToSameAccount\" : true\r\n    }\r\n  }, {\r\n    \"minSum\" : 5000,\r\n    \"maxSum\" : 5000000,\r\n    \"financialProduct\" : {\r\n      \"period\" : 62,\r\n      \"canWithdrawal\" : true,\r\n      \"name\" : \"АТБ. Вклад\",\r\n      \"currency\" : \"RUB\",\r\n      \"id\" : 12345,\r\n      \"canDeposit\" : true,\r\n      \"category\" : \"Клиент\",\r\n      \"percent\" : 15.3,\r\n      \"capitalizationPeriod\" : \"Ежедневно\",\r\n      \"capitalizationToSameAccount\" : true\r\n    }\r\n  } ]\r\n}",
                            FinancialProductsResponseDto.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn(
                "ObjectMapper or HttpServletRequest not configured in default FinancialProductsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

